#! /usr/bin/env expect

set timeout -1

spawn qemu-system-x86_64 \
    -no-kvm \
    -machine pc \
    -cpu qemu64 \
    -accel tcg \
    -drive file=qemu/zbox.img,format=raw,cache=directsync \
    -nographic

expect -ex {zbox login: }
send "root\n"
expect -ex {zbox:~# }
send "rm -rf data zbox-fail-test-repo zbox-fail-test\n"
expect -ex {zbox:~# }
send "dd if=/dev/urandom of=data bs=1M count=16\n"
expect -ex {zbox:~# }
send "wget https://github.com/fin-ger/zbox-fail-test/releases/download/v0.4.0/zbox-fail-test\n"
expect -ex {zbox:~# }
send "chmod +x zbox-fail-test\n"
expect -ex {zbox:~# }
send "RUST_LOG=zbox=trace RUST_BACKTRACE=1 ./zbox-fail-test --file data run\n"
expect -ex {Writing chunk 7 to repository (1MiB)...}
exit
