#! /usr/bin/env expect

set timeout -1

spawn qemu-system-x86_64 \
    -no-kvm \
    -machine pc \
    -cpu qemu64 \
    -accel tcg \
    -drive file=qemu/zbox.img,format=raw \
    -nographic

expect -ex {zbox login: }
send "root\n"
expect -ex {zbox:~# }
send "rm -rf data zbox-fail-test-repo zbox-fail-test\n"
expect -ex {zbox:~# }
send "dd if=/dev/urandom of=data bs=1K count=128\n"
expect -ex {zbox:~# }
send "wget https://github.com/fin-ger/zbox-fail-test/releases/download/v0.1.0/zbox-fail-test\n"
expect -ex {zbox:~# }
send "chmod +x zbox-fail-test\n"
expect -ex {zbox:~# }
send "RUST_BACKTRACE=1 ./zbox-fail-test --file data run\n"
expect -ex {Writing chunk 0 to repository (1MiB)...}
sleep 60
exit
